package com.muffinapps.textyofriends.models;

import java.util.Date;

import io.realm.RealmObject;

/**
 * Created by aakash on 8/28/15.
 */
public class Contact extends RealmObject {

    private Date createdAt;
    private Date updatedAt;
    private String name;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public int    getAge() { return age; }
    public void   setAge(int age) { this.age = age; }
    public int    getSessionId() { return sessionId; }
    public void   setSessionId(int dontPersist) { this.sessionId = sessionId; }
}


